#!/usr/bin/perl -w
use strict;
use warnings;

# FIXME: This hard coded thing makes this unportable
chdir '/home/dav/PerlDAV' or die $!;

use lib('/home/dav/PerlDAV');

use WebDAV;
WebDAV::initialiseServer();
WebDAV::runServer();
