#!/usr/bin/perl -w
use strict;
use warnings;
use WDGlobals qw|PWD|;

# FIXME: This hard coded thing makes this unportable
chdir $PWD or die "$! 'chdir $PWD' failed ";

use lib($PWD);

use WebDAV;
WebDAV::initialiseServer();
WebDAV::runServer();
